#-------------------------------
# General Site Settings

title: Sharon Brizinov
description: Software Developer // Security Researcher // Entrepreneur
email: Sharon.Brizinov+Job@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}
- {name: Linkedin, url: 'https://www.linkedin.com/in/sharon-brizinov-808b9753'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A software developer with a strong passion to web, mobile applications, security research, and science.'
  rel-author: 'http://www.sharonbrizinov.com'
  rel-publisher: 'http://www.sharonbrizinov.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-23237683-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Sharon specializes in making awesome products.**
  Most of the things he develops are [mobile applications](https://itunes.apple.com/il/developer/sharon-brizinov/id435609791){:target="_blank"},
  but he also puts effort into [security research](http://fullstacks.io){:target="_blank"}
  and [open source projects](https://github.com/SharonBrizinov){:target="_blank"}.


#-------------------------------
# Work Section

projects:
- {name: Yo - Modern Simon Says (Game), folder: 'proj-1', url: 'http://www.hashtagyo.com/'}
- {name: Meme+ Pro - Meme Generator & SoundPad (iOS), folder: 'proj-2', url: 'https://itunes.apple.com/us/app/meme+-pro-meme-generator-soundpad/id488702679?mt=8'}
- {name: Geometry 2D (iOS), folder: 'proj-3', url: 'https://itunes.apple.com/us/app/geometry-2d/id441907476?mt=8'}
- {name: TestGloss (iOS), folder: 'proj-4', url: 'https://itunes.apple.com/us/app/testgloss/id502302350?mt=8'}
- {name: Inviter (iOS), folder: 'proj-5', url: 'https://itunes.apple.com/il/app/inviter-hzmnwt-w-yswry-hg-h/id905097504?mt=8'}
- {name: Asteroids (Game), folder: 'proj-6', url: 'https://github.com/SharonBrizinov/Asteroids'}
- {name: iCopter (ASM), folder: 'proj-7', url: 'https://github.com/SharonBrizinov/iCopter'}
- {name: Whatsapp Analyzer (iOS), folder: 'proj-8', url: 'https://github.com/SharonBrizinov/Whatsapp-Analyzer'}



# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
